package com.trinhquycong.restloginreviewcenter.model;
// Generated Dec 11, 2021, 7:48:03 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.trinhquycong.restloginreviewcenter.dto.RateNumber;
import com.trinhquycong.restloginreviewcenter.util.RateNumberConverter;

import lombok.Getter;
import lombok.Setter;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(schema = "reviewcenter", name = "ratings")
@Getter
@Setter
public class Rating implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@SequenceGenerator(name="seq_rating",sequenceName="seq_rating_optional", allocationSize=1)
	@GeneratedValue(strategy= GenerationType.SEQUENCE, generator="seq_rating")
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "center_id", nullable = false)
	private Center center;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	private User user;
	
	@Column(name = "rate", nullable = false)
	@Convert(converter = RateNumberConverter.class)
	private RateNumber rate;
	
	@Column(name = "comment", nullable = false)
	private String comment;
	
	@Column(name = "enabled")
	private Boolean enabled;

    @Temporal(TemporalType.TIMESTAMP)
    protected Date createdDate;
    
    @Temporal(TemporalType.TIMESTAMP)
    protected Date modifiedDate;

}
